Name: Deploy to Hugging Face SpaceName: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        env:
          HAGGING_FUCE: ${{ secrets.HAGGING_FUCE }}
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "BumbleBeeDubDudu"

          git clone https://huggingface.co/spaces/BumbleBeeDubDudu/stegologo hf_space

          rsync -av --exclude='.git' --exclude='hf_space' ./ hf_space/

          cd hf_space
          git remote set-url origin https://BumbleBeeDubDudu:${HAGGING_FUCE}@huggingface.co/spaces/BumbleBeeDubDudu/stegologo

          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes"
          git push origin main
